module
import Solution

#check @BayesCorrelated.finite_characterization
#check @BayesCorrelated.mixedBNE_induces_BCE
#check @BayesCorrelated.expansion_normalized
#check @BayesCorrelated.expansion_null_fiber
#check @BayesCorrelated.strategyProduct_isProbability
#check @BayesCorrelated.induces_iff_positive_support
#check @BayesCorrelated.onePlayer_obedienceGain
#check @BayesCorrelated.onePlayer_characterization
#check @BayesCorrelated.information_order_characterization
#check @BayesCorrelated.individuallySufficient_outcome
#check @BayesCorrelated.moreIncentiveConstrained_outcome_any_universe
#check @BayesCorrelated.onePlayer_individual_sufficiency
#check @BayesCorrelated.onePlayer_information_order
#check @BayesCorrelated.IsProbability
#check @BayesCorrelated.IsInformation
#check @BayesCorrelated.IsDecisionRule
#check @BayesCorrelated.obedienceGain
#check @BayesCorrelated.BCE
#check @BayesCorrelated.IsExpansion
#check @BayesCorrelated.IsStrategy
#check @BayesCorrelated.strategyProduct
#check @BayesCorrelated.Induces
#check @BayesCorrelated.bestResponseGain
#check @BayesCorrelated.MixedBNE
#check @BayesCorrelated.Implementable
#check @BayesCorrelated.IsCombination
#check @BayesCorrelated.HasIndividualChannels
#check @BayesCorrelated.IndividuallySufficient
#check @BayesCorrelated.FullSupportPrior
#check @BayesCorrelated.outcome
#check @BayesCorrelated.IsBCEOutcome
#check @BayesCorrelated.MoreIncentiveConstrained
#check @BayesCorrelated.IsGarbling
